# Cleaning and Exploring the Dataset

In [1]:
import pandas as pd

## Loading the data

In [2]:
dataset = pd.read_csv("../data/Assessment_Parcels_20261010.csv")

C:\Users\maazk\AppData\Local\Temp\ipykernel_15148\2222640743.py:1: DtypeWarning: Columns (2: Unit Number, 3: Street Suffix, 4: Street Direction, 39: Property Class 3, 40: Status 3, 41: Assessed Value 3, 42: Property Class 4, 43: Status 4, 44: Assessed Value 4, 45: Property Class 5, 46: Status 5, 47: Assessed Value 5) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("../data/Assessment_Parcels_20261010.csv")

## Exploring the Data

### Dataset overview

In [3]:
dataset.shape

(245487, 71)

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 245487 entries, 0 to 245486
Data columns (total 71 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Roll Number                      245487 non-null  int64
 1   Street Number                    240494 non-null  str
 2   Unit Number                      27228 non-null   object
 3   Street Suffix                    636 non-null     str
 4   Street Direction                 12088 non-null   str
 5   Street Name                      242300 non-null  str
 6   Street Type                      241630 non-null  str
 7   Full Address                     242300 non-null  str
 8   Neighbourhood Area               245455 non-null  str
 9   Market Region                    245487 non-null  str
 10  Total Living Area                222920 non-null  str
 11  Building Type                    195847 non-null  str
 12  Basement                         222898 non-null  str
 13  Basement Finish                  222995 non-null  str
 14  Year Built                       222920 non-null  float64
 15  Rooms                            222911 non-null  float64
 16  Air Conditioning                 195847 non-null  str
 17  Fire Place                       222995 non-null  str
 18  Attached Garage                  195919 non-null  str
 19  Detached Garage                  195919 non-null  str
 20  Pool                             195919 non-null  str
 21  Number Floors (Condo)            27073 non-null   float64
 22  Property Use Code                245487 non-null  str
 23  Assessed Land Area               216978 non-null  str
 24  Water Frontage Measurement       237282 non-null  str
 25  Sewer Frontage Measurement       237189 non-null  str
 26  Property Influences              117811 non-null  str
 27  Zoning                           217645 non-null  str
 28  Total Assessed Value             244644 non-null  str
 29  Total Proposed Assessment Value  0 non-null       float64
 30  Assessment Date                  245487 non-null  str
 31  Detail URL                       245487 non-null  str
 32  Current Assessment Year          245487 non-null  int64
 33  Property Class 1                 244644 non-null  str
 34  Status 1                         244644 non-null  str
 35  Assessed Value 1                 244644 non-null  str
 36  Property Class 2                 2146 non-null    str
 37  Status 2                         2146 non-null    str
 38  Assessed Value 2                 2146 non-null    str
 39  Property Class 3                 102 non-null     str
 40  Status 3                         102 non-null     str
 41  Assessed Value 3                 102 non-null     str
 42  Property Class 4                 11 non-null      str
 43  Status 4                         11 non-null      str
 44  Assessed Value 4                 11 non-null      str
 45  Property Class 5                 1 non-null       str
 46  Status 5                         1 non-null       str
 47  Assessed Value 5                 1 non-null       str
 48  Proposed Assessment Year         0 non-null       float64
 49  Proposed Assessment Date         0 non-null       float64
 50  Proposed Property Class 1        0 non-null       float64
 51  Proposed Status 1                0 non-null       float64
 52  Proposed Assessment Value 1      0 non-null       float64
 53  Proposed Property Class 2        0 non-null       float64
 54  Proposed Status 2                0 non-null       float64
 55  Proposed Assessment Value 2      0 non-null       float64
 56  Proposed Property Class 3        0 non-null       float64
 57  Proposed Status 3                0 non-null       float64
 58  Proposed Assessment Value 3      0 non-null       float64
 59  Proposed Property Class 4        0 non-null       float64
 60  Proposed Status 4                0 non-null       float64
 61  Proposed Assessment Value 4      0 non-null       float64
 62  Proposed Property Class 5        0 non-null       float64
 63  Proposed Status 5                0 non-null       float64
 64  Proposed Assessment Value 5      0 non-null       float64
 65  Multiple Residences              222995 non-null  str
 66  Geometry                         245424 non-null  str
 67  Dwelling Units                   244644 non-null  float64
 68  Centroid Lat                     245424 non-null  float64
 69  Centroid Lon                     245424 non-null  float64
 70  GISID                            245424 non-null  str
dtypes: float64(24), int64(2), object(1), str(44)
memory usage: 344.0+ MB

### Data types for Specific columns

I will inspect Total Assessed Value, Total Living Area, and Assessed Land Area first because they are the target and key features.

In [5]:
dataset["Total Assessed Value"].head(10)

0      $893,000.00
1       $55,000.00
2    $1,994,000.00
3      $650,000.00
4      $968,000.00
5      $663,000.00
6    $1,208,000.00
7    $2,185,000.00
8    $1,210,000.00
9      $620,000.00
Name: Total Assessed Value, dtype: str

I think the cause for this column to be string datatype is "$" and "," in every value.

In [6]:
dataset["Total Living Area"].head(10)

0    1,313
1      NaN
2    4,007
3    1,052
4    3,120
5    1,510
6    4,570
7    4,932
8    2,773
9    1,396
Name: Total Living Area, dtype: str

In [7]:
dataset["Assessed Land Area"].head(10)

0    197,030
1          1
2    218,155
3     43,628
4    130,705
5    130,718
6    131,116
7    105,687
8    105,675
9    105,663
Name: Assessed Land Area, dtype: str

I think the cause for this two column to be string datatype is "," in every value.

~ I will remove $ and , from the text and convert the column to numeric values during the data-cleaning stage.

### Property types

In [8]:
dataset["Building Type"].value_counts()

Building Type
ONE STOREY          92342
TWO STOREY          50605
ONE & 1/2 STOREY    17683
BI-LEVEL            11556
ONE & 3/4 STOREY     5485
4 LEVEL SPLIT        5199
TWO & 1/2 STOREY     4187
CABOVER              4038
TWO/ONE STOREY       2519
3 LEVEL SPLIT        2176
THREE STOREY           57
Name: count, dtype: int64

All 11 values are house styles. Nothing commercial.

In [9]:
dataset["Property Use Code"].value_counts()

Property Use Code
RESSD - DETACHED SINGLE DWELLING    177823
CNAPT - CONDO APARTMENT              20788
RESSS - SIDE BY SIDE                  9798
CNRES - CONDO RESIDENTIAL             6288
VRES1 - VACANT RESIDENTIAL 1          5983
                                     ...
PIRRT - RACE TRACK                       2
PIRBA - BOWLING ALLEY                    2
PIIRE - REMAND FACILITY                  2
STATU - STATUTORY ASSESSMENT             1
PERP - PERSONAL PROPERTY                 1
Name: count, Length: 100, dtype: int64

Property Use Code has 100 categories, with RESSD (detached single dwelling) dominating at 177.8K rows, while the rest include condos, duplexes, vacant land, and other properties like racetracks and bowling alleys.

~ I will filter by Property Use Code and use only RESSD (detached single dwellings) for the first version, then consider adding RESSS later.

### Missing Values & Leakage check

In [10]:
ressd_data = dataset[dataset["Property Use Code"] == "RESSD - DETACHED SINGLE DWELLING"]

In [11]:
ressd_data.head()

,Roll Number,Street Number,Unit Number,Street Suffix,Street Direction,Street Name,Street Type,Full Address,Neighbourhood Area,Market Region,...,Proposed Assessment Value 4,Proposed Property Class 5,Proposed Status 5,Proposed Assessment Value 5,Multiple Residences,Geometry,Dwelling Units,Centroid Lat,Centroid Lon,GISID
0,1000001000,"1,636",NaN,NaN,NaN,MCCREARY,ROAD,1636 MCCREARY ROAD,WILKES SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.23311670618891 49.83063124...,1.0,49.830137,-97.234696,"148,170"
2,1000005500,"1,584",NaN,NaN,NaN,MCCREARY,ROAD,1584 MCCREARY ROAD,WILKES SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.2361802081971 49.831882231...,1.0,49.831649,-97.234565,"148,168"
3,1000008000,"1,574",NaN,NaN,NaN,MCCREARY,ROAD,1574 MCCREARY ROAD,WILKES SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.23616667174454 49.83203713...,1.0,49.832113,-97.234524,"185,348"
4,1000008200,"1,550",NaN,NaN,NaN,MCCREARY,ROAD,1550 MCCREARY ROAD,WILKES SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.23612611966252 49.83250120...,1.0,49.832423,-97.234497,"185,347"
5,1000008400,"1,538",NaN,NaN,NaN,MCCREARY,ROAD,1538 MCCREARY ROAD,WILKES SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.23608555720466 49.83296537...,1.0,49.832887,-97.234457,"185,346"

In [12]:
ressd_data.shape

(177823, 71)

In [13]:
print(ressd_data.isnull().sum().to_string())

Roll Number                             0
Street Number                           1
Unit Number                        177811
Street Suffix                      177719
Street Direction                   169002
Street Name                             0
Street Type                           480
Full Address                            0
Neighbourhood Area                      0
Market Region                           0
Total Living Area                      56
Building Type                          56
Basement                               79
Basement Finish                         0
Year Built                             56
Rooms                                  62
Air Conditioning                       56
Fire Place                              0
Attached Garage                         0
Detached Garage                         0
Pool                                    0
Number Floors (Condo)              177823
Property Use Code                       0
Assessed Land Area                      0
Water Frontage Measurement           1318
Sewer Frontage Measurement           1379
Property Influences                 89948
Zoning                                  4
Total Assessed Value                    0
Total Proposed Assessment Value    177823
Assessment Date                         0
Detail URL                              0
Current Assessment Year                 0
Property Class 1                        0
Status 1                                0
Assessed Value 1                        0
Property Class 2                   177689
Status 2                           177689
Assessed Value 2                   177689
Property Class 3                   177820
Status 3                           177820
Assessed Value 3                   177820
Property Class 4                   177823
Status 4                           177823
Assessed Value 4                   177823
Property Class 5                   177823
Status 5                           177823
Assessed Value 5                   177823
Proposed Assessment Year           177823
Proposed Assessment Date           177823
Proposed Property Class 1          177823
Proposed Status 1                  177823
Proposed Assessment Value 1        177823
Proposed Property Class 2          177823
Proposed Status 2                  177823
Proposed Assessment Value 2        177823
Proposed Property Class 3          177823
Proposed Status 3                  177823
Proposed Assessment Value 3        177823
Proposed Property Class 4          177823
Proposed Status 4                  177823
Proposed Assessment Value 4        177823
Proposed Property Class 5          177823
Proposed Status 5                  177823
Proposed Assessment Value 5        177823
Multiple Residences                     0
Geometry                                0
Dwelling Units                          0
Centroid Lat                            0
Centroid Lon                            0
GISID                                   0

Among detached houses, missing values fall into three groups:

* Completely empty (100% missing): Number Floors (Condo), Property Class/Status/Assessed Value 4 and 5, Total Proposed Assessment Value, and all other Proposed fields. These will be dropped.
* Mostly missing: Unit Number, Street Suffix, and Street Direction (about 95% missing or more), plus Property Class/Status/Assessed Value 2 and 3.
* Small gaps in key columns: Total Living Area, Year Built, Building Type, and Air Conditioning each have 56 missing (the same rows for Living Area and Year Built). Rooms, Basement, and the frontage columns have small gaps as well. Property Influences is about 50% missing, which probably means “none,” so it needs a different decision.

In [14]:

missing_area = ressd_data[ressd_data["Total Living Area"].isnull()]
print(missing_area[["Total Living Area", "Year Built"]].isnull().sum())

Total Living Area    56
Year Built           56
dtype: int64

The 56 missing values in Total Living Area and Year Built are in the same rows.

In [15]:
ressd_data[["Assessed Value 1", "Total Assessed Value"]].head()

  Assessed Value 1 Total Assessed Value
0      $893,000.00          $893,000.00
2    $1,994,000.00        $1,994,000.00
3      $650,000.00          $650,000.00
4      $968,000.00          $968,000.00
5      $663,000.00          $663,000.00

“Assessed Value 1 is identical to Total Assessed Value in the rows checked, so it is leakage and will be dropped from the features.

In [16]:
missing_area[["Total Assessed Value","Assessed Land Area","Building Type"]].head()

      Total Assessed Value Assessed Land Area Building Type
47764          $179,000.00              4,486           NaN
47768          $179,000.00              4,486           NaN
48011          $145,000.00              4,014           NaN
48031          $145,000.00              4,016           NaN
65966          $144,000.00              3,905           NaN

The 56 rows missing Total Living Area and Year Built (and Building Type) are likely land-only parcels with low values. we will drop them.

### Data types

In [17]:
print(ressd_data.dtypes.to_string())

Roll Number                          int64
Street Number                          str
Unit Number                         object
Street Suffix                          str
Street Direction                       str
Street Name                            str
Street Type                            str
Full Address                           str
Neighbourhood Area                     str
Market Region                          str
Total Living Area                      str
Building Type                          str
Basement                               str
Basement Finish                        str
Year Built                         float64
Rooms                              float64
Air Conditioning                       str
Fire Place                             str
Attached Garage                        str
Detached Garage                        str
Pool                                   str
Number Floors (Condo)              float64
Property Use Code                      str
Assessed Land Area                     str
Water Frontage Measurement             str
Sewer Frontage Measurement             str
Property Influences                    str
Zoning                                 str
Total Assessed Value                   str
Total Proposed Assessment Value    float64
Assessment Date                        str
Detail URL                             str
Current Assessment Year              int64
Property Class 1                       str
Status 1                               str
Assessed Value 1                       str
Property Class 2                       str
Status 2                               str
Assessed Value 2                       str
Property Class 3                       str
Status 3                               str
Assessed Value 3                       str
Property Class 4                       str
Status 4                               str
Assessed Value 4                       str
Property Class 5                       str
Status 5                               str
Assessed Value 5                       str
Proposed Assessment Year           float64
Proposed Assessment Date           float64
Proposed Property Class 1          float64
Proposed Status 1                  float64
Proposed Assessment Value 1        float64
Proposed Property Class 2          float64
Proposed Status 2                  float64
Proposed Assessment Value 2        float64
Proposed Property Class 3          float64
Proposed Status 3                  float64
Proposed Assessment Value 3        float64
Proposed Property Class 4          float64
Proposed Status 4                  float64
Proposed Assessment Value 4        float64
Proposed Property Class 5          float64
Proposed Status 5                  float64
Proposed Assessment Value 5        float64
Multiple Residences                    str
Geometry                               str
Dwelling Units                     float64
Centroid Lat                       float64
Centroid Lon                       float64
GISID                                  str

In [18]:
print(ressd_data.nunique().to_string())

Roll Number                        177823
Street Number                        3466
Unit Number                             9
Street Suffix                           3
Street Direction                        4
Street Name                          3779
Street Type                            35
Full Address                       177724
Neighbourhood Area                    203
Market Region                          10
Total Living Area                    3634
Building Type                          11
Basement                                2
Basement Finish                         2
Year Built                            150
Rooms                                  21
Air Conditioning                        2
Fire Place                              2
Attached Garage                         2
Detached Garage                         2
Pool                                    2
Number Floors (Condo)                   0
Property Use Code                       1
Assessed Land Area                  14837
Water Frontage Measurement           2011
Sewer Frontage Measurement           1921
Property Influences                  1311
Zoning                                 37
Total Assessed Value                 1932
Total Proposed Assessment Value         0
Assessment Date                         1
Detail URL                         177823
Current Assessment Year                 1
Property Class 1                        4
Status 1                                4
Assessed Value 1                     1931
Property Class 2                        6
Status 2                                3
Assessed Value 2                       88
Property Class 3                        2
Status 3                                2
Assessed Value 3                        3
Property Class 4                        0
Status 4                                0
Assessed Value 4                        0
Property Class 5                        0
Status 5                                0
Assessed Value 5                        0
Proposed Assessment Year                0
Proposed Assessment Date                0
Proposed Property Class 1               0
Proposed Status 1                       0
Proposed Assessment Value 1             0
Proposed Property Class 2               0
Proposed Status 2                       0
Proposed Assessment Value 2             0
Proposed Property Class 3               0
Proposed Status 3                       0
Proposed Assessment Value 3             0
Proposed Property Class 4               0
Proposed Status 4                       0
Proposed Assessment Value 4             0
Proposed Property Class 5               0
Proposed Status 5                       0
Proposed Assessment Value 5             0
Multiple Residences                     2
Geometry                           177822
Dwelling Units                          4
Centroid Lat                       177822
Centroid Lon                       177822
GISID                              177822

The data type audit found several columns stored as the wrong type:
- **Numbers stored as text:** Total Living Area, Assessed Land Area, Total Assessed Value, and the frontage measurements contain "$" or "," characters and must be converted to numbers.
- **Whole numbers stored as decimals:** Year Built and Rooms are floats only because of missing values and will become integers after the missing rows are dropped.
- **Identifier columns:** Roll Number, Street Number, Full Address, Detail URL, Geometry, and GISID identify properties and will not be used as model features.

In [19]:
ressd_data["Air Conditioning"].value_counts()

Air Conditioning
Yes    133580
No      44187
Name: count, dtype: int64

In [20]:
ressd_data["Pool"].value_counts()

Pool
No     172027
Yes      5796
Name: count, dtype: int64

In [21]:
ressd_data["Multiple Residences"].value_counts()

Multiple Residences
No     177822
Yes         1
Name: count, dtype: int64

Air Conditioning, Pool, Multiple Resideences we will encode as 1/0.The same encoding will be used for the other Yes/No columns (Basement, Basement Finish, Fire Place, Attached Garage, Detached Garage) after confirming their values.

### Outliers and suspicious values

I will use .describe() on Year Built and Rooms first.
After converting the other measurement columns to numbers during cleaning, I will use .describe() and check for outliers.

In [22]:
ressd_data[["Year Built", "Rooms"]].describe()

          Year Built          Rooms
count  177767.000000  177761.000000
mean     1966.452542       6.099909
std        32.138645       1.325768
min      1870.000000       1.000000
25%      1948.000000       5.000000
50%      1967.000000       6.000000
75%      1988.000000       7.000000
max      2026.000000      24.000000

Year Built ranges from 1870 to 2026, with a median of 1967. No impossible years were found, but I will check the houses built in 2026.
Rooms range from 1 to 24, but most houses have 5–7 rooms. I will check the very low and high values for possible errors or outliers.

In [23]:
ressd_data["Property Class 1"].value_counts()

Property Class 1
RESIDENTIAL 1    177816
INSTITUTIONAL         3
RESIDENTIAL 3         3
OTHER                 1
Name: count, dtype: int64

In [24]:
ressd_data["Status 1"].value_counts()

Status 1
TAXABLE                  177695
GRANT                        98
EXEMPT                       26
TAXABLE SCHOOL EXEMPT         4
Name: count, dtype: int64

Property Class 1 and Status 1 are almost constant and describe tax information, so I will drop them.
I will also check the 7 houses with unusual property classes before deciding whether to remove them.

In [25]:
ressd_data["Dwelling Units"].value_counts()

Dwelling Units
1.0    177749
0.0        66
2.0         7
3.0         1
Name: count, dtype: int64

Dwelling Units is 1 for almost all houses, so I will not use it as a feature.
I will check the 0-unit rows to see if they match the 56 rows with missing building data.

In [26]:
print("Rooms <= 2:", (ressd_data["Rooms"] <= 2).sum())
print("Rooms >= 15:", (ressd_data["Rooms"] >= 15).sum())

Rooms <= 2: 30
Rooms >= 15: 29

30 houses have 2 or fewer rooms and 29 have 15 or more. These are rare cases, so I will check their living area and assessed value before deciding what to do.

In [27]:
ressd_data[ressd_data["Year Built"] == 2026].head()

,Roll Number,Street Number,Unit Number,Street Suffix,Street Direction,Street Name,Street Type,Full Address,Neighbourhood Area,Market Region,...,Proposed Assessment Value 4,Proposed Property Class 5,Proposed Status 5,Proposed Assessment Value 5,Multiple Residences,Geometry,Dwelling Units,Centroid Lat,Centroid Lon,GISID
10391,1009605105,97,NaN,NaN,NaN,ZIMMERMAN,DRIVE,97 ZIMMERMAN DRIVE,RIDGEWOOD SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.32322270994209 49.84180035...,1.0,49.841736,-97.322931,"635,831"
10648,1009606430,188,NaN,NaN,NaN,ZIMMERMAN,DRIVE,188 ZIMMERMAN DRIVE,RIDGEWOOD SOUTH,"6, CHARLESWOOD",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.3219163721806 49.840349760...,1.0,49.840190,-97.321980,"646,548"
66302,4007270440,141,NaN,NaN,NaN,KEN BUTCHART,CRESCENT,141 KEN BUTCHART CRESCENT,PEGUIS,"1, TRANSCONA",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.03697221314408 49.91169441...,1.0,49.911647,-97.037221,"651,809"
80778,5009441935,362,NaN,NaN,NaN,AVIOR,DRIVE,362 AVIOR DRIVE,W K INDUSTRIAL,"3, WEST KILDONAN / OLD KILDONAN",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.11813664605515 49.95937999...,1.0,49.959186,-97.118266,"656,103"
102148,6093470335,15,NaN,NaN,NaN,STONEKNIFE,CRESCENT,15 STONEKNIFE CRESCENT,SAGE CREEK,"10, NEW ST BONIFACE/NEW ST VITAL",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.0356788457519 49.821324716...,1.0,49.821205,-97.035904,"639,415"

Houses built in 2026 are mostly in newer neighbourhoods, so they are likely new homes.
I will check their living area and assessed value to make sure the records are complete.

In [28]:
len(ressd_data[ressd_data["Dwelling Units"] == 0])

66

In [29]:
zero_units = ressd_data[ressd_data["Dwelling Units"] == 0]
zero_units["Total Living Area"].isnull().sum()

np.int64(56)

56 houses with 0 dwelling units are also missing Total Living Area, so I will drop them.
The remaining 10 houses have building data, so I will check them separately.

In [30]:
new_homes = ressd_data[ressd_data["Year Built"] == 2026]
len(new_homes)

11

In [31]:
new_homes[['Full Address', 'Total Living Area', 'Rooms', 'Total Assessed Value']]

,Full Address,Total Living Area,Rooms,Total Assessed Value
10391,97 ZIMMERMAN DRIVE,"1,802",7.0,"$630,000.00"
10648,188 ZIMMERMAN DRIVE,"1,611",6.0,"$581,000.00"
66302,141 KEN BUTCHART CRESCENT,"1,820",8.0,"$598,000.00"
80778,362 AVIOR DRIVE,"1,696",8.0,"$609,000.00"
102148,15 STONEKNIFE CRESCENT,"1,934",8.0,"$650,000.00"
130828,259 VICTORIA CRESCENT,"3,214",8.0,"$1,678,000.00"
138391,74 VAN HULL WAY,"2,501",9.0,"$910,000.00"
140298,570 CHRISTIE ROAD,"6,109",10.0,"$2,808,000.00"
140409,85 JEAN LOUIS ROAD,"7,175",12.0,"$3,016,000.00"
162570,202 HORTON AVENUE W,"1,311",6.0,"$427,000.00"
162861,19 DOVETAIL CRESCENT,"1,663",6.0,"$562,000.00"

All 11 houses with Year Built = 2026 have normal living areas (1,311 to 7,175 sq ft), 6 to 12 rooms, and assessed values from $427,000 to about $3.0 million, so they appear to be complete records of newly built homes. They will be kept.

In [32]:
two_rooms = ressd_data[ressd_data["Rooms"] <= 2]
two_rooms[['Full Address', 'Total Living Area', 'Rooms', 'Total Assessed Value']].head()

               Full Address Total Living Area  Rooms Total Assessed Value
3948  4515 ROBLIN BOULEVARD             3,258    1.0        $1,610,000.00
4137      753 COVENTRY ROAD             2,362    1.0          $682,000.00
6869      45 PARADISE DRIVE             2,956    1.0          $683,000.00
6892  6475 SOUTHBOINE DRIVE             4,131    1.0        $1,471,000.00
9056      910 ELMHURST ROAD             1,540    2.0          $507,000.00

30 houses report 2 or fewer rooms, but the ones inspected have large living areas (1,540 to 4,131 sq ft) and assessed values from about 507,000 to 1.6 million. A one-room house with 4,131 sq ft is not realistic, so the Rooms value is a data error rather than a sign of a tiny property. These rows will be dropped, since only 30 rows (about 0.02% of the data) are affected.

In [33]:
zero_unit_houses = ressd_data[
    (ressd_data["Dwelling Units"] == 0) &
    (ressd_data["Total Living Area"].notnull())
]

zero_unit_houses[[
    "Full Address",
    "Total Living Area",
    "Rooms",
    "Total Assessed Value"
]]

                  Full Address Total Living Area  Rooms Total Assessed Value
80206         143 NUTHATCH BAY             1,976    8.0                $0.00
80282       87 GROUSE CRESCENT             1,770    7.0          $600,000.00
91324      509 PLINGUET STREET               616    4.0          $226,000.00
93909     246 ENFIELD CRESCENT             1,100    6.0          $154,000.00
103679   165 CINNAMON TEAL WAY             2,675    7.0          $256,000.00
194542  212 KENASTON BOULEVARD             1,144    6.0          $273,000.00
218792        135 GROVE STREET             1,412    7.0           $30,000.00
226075     427 ANDERSON AVENUE             1,456    8.0           $90,000.00
231584   109 INKSTER BOULEVARD             1,150    5.0          $151,000.00
237262        386 NAIRN AVENUE             1,039    5.0          $120,000.00

10 houses have 0 dwelling units but do have living area and room counts. Their assessed values are inconsistent with their size: one is 0 and several are between 30,000 and 154,000 for houses of 1,100 to 1,450 sq ft. These look like partial or unusual assessments, so they will be dropped. This also shows that Total Assessed Value needs an outlier check (very low values) after it is converted to a number.

In [34]:
fifteen_Rooms = ressd_data[ressd_data["Rooms"] >= 15]
fifteen_Rooms[['Full Address', 'Total Living Area', 'Rooms', 'Total Assessed Value']]

                   Full Address Total Living Area  Rooms Total Assessed Value
4576            34 LANNOO DRIVE             6,983   15.0        $1,026,000.00
77439              66 NIHAL BAY            10,229   16.0        $2,147,000.00
83222     158 SOUTHBRIDGE DRIVE             3,700   15.0        $1,261,000.00
95364        110 ST MARY'S ROAD             2,624   16.0          $525,000.00
106197           473 FERRY ROAD             2,548   15.0          $503,000.00
130784    122 VICTORIA CRESCENT             5,990   20.0        $3,006,000.00
165539     121 PARK BOULEVARD N             4,429   16.0        $2,343,000.00
165965   103 HANDSART BOULEVARD             5,104   16.0        $1,672,000.00
166638     570 PARK BOULEVARD W            11,197   16.0        $2,532,000.00
169702     550 PARK BOULEVARD W             9,860   18.0        $5,579,000.00
187302      34 AVONHERST STREET             5,730   15.0        $1,208,000.00
187332           50 YALE AVENUE             5,337   15.0        $1,122,000.00
187358          288 YALE AVENUE             3,464   15.0          $653,000.00
187576              53 KINGSWAY             4,115   15.0          $435,000.00
187583              12 KINGSWAY             7,409   19.0        $1,893,000.00
187593  657 WELLINGTON CRESCENT             5,902   16.0          $895,000.00
187731       201 DROMORE AVENUE             6,510   15.0        $1,625,000.00
188889  970 WELLINGTON CRESCENT             4,618   15.0        $1,258,000.00
196146      542 GREENWOOD PLACE             2,478   15.0          $428,000.00
197539      853 WOLSELEY AVENUE             3,104   16.0          $411,000.00
198743             39 EAST GATE             6,017   17.0        $1,271,000.00
198748             89 EAST GATE             8,172   20.0        $1,075,000.00
198767            134 WEST GATE             4,422   15.0        $1,177,000.00
198780            157 WEST GATE             4,744   15.0          $958,000.00
198832           67 MIDDLE GATE             4,036   15.0          $793,000.00
198847             90 EAST GATE             5,930   20.0          $567,000.00
200003              5 EAST GATE             6,531   16.0        $1,457,000.00
211970        477 SPENCE STREET             4,564   24.0          $351,000.00
215312         99 GEORGE AVENUE             3,717   15.0          $217,000.00

29 houses have 15 or more rooms. Most have large living areas (2,478 to 11,197 sq ft) and are located in established neighbourhoods, so these appear to be genuinely large or older homes rather than data errors. Two (477 Spence Street and 99 George Avenue) have low assessed values for their size and may be rooming houses or homes in poor condition. All will be kept for now and revisited during model error analysis.

In [35]:
columns = ["Basement", "Basement Finish", "Fire Place", "Attached Garage", "Detached Garage"]

for col in columns:
    print(f"\n{col}:")
    print(ressd_data[col].value_counts(dropna=False))

Basement:
Basement
Yes    173857
No       3887
NaN        79
Name: count, dtype: int64

Basement Finish:
Basement Finish
Yes    128240
No      49583
Name: count, dtype: int64

Fire Place:
Fire Place
No     120380
Yes     57443
Name: count, dtype: int64

Attached Garage:
Attached Garage
No     116308
Yes     61515
Name: count, dtype: int64

Detached Garage:
Detached Garage
No     94555
Yes    83268
Name: count, dtype: int64

Basement, Basement Finish, Fire Place, Attached Garage, and Detached Garage are all clean Yes/No columns with no unexpected values, so each can be encoded as 1/0. Only Basement has missing values (79). Basement is "Yes" for 96% of houses, so it adds little information on its own, while Basement Finish, Fire Place, and both garage columns are more evenly split and are likely more useful for prediction.

In [36]:
((ressd_data["Basement"] == "No") & (ressd_data["Basement Finish"] == "Yes")).sum()

np.int64(0)

In [37]:
(ressd_data["Basement"].isnull() & ressd_data["Total Living Area"].isnull()).sum()

np.int64(56)

No house has Basement = "No" together with Basement Finish = "Yes", so the two columns are consistent. Of the 79 houses with a missing Basement value, 56 are the land-only rows that will be dropped. The remaining 23 rows (about 0.01% of the data) will be handled after the drop, either by dropping them or by filling with the most common value ("Yes").

### Messy text columns

In [38]:
check = ressd_data[ressd_data[["Water Frontage Measurement", "Sewer Frontage Measurement"]].notnull().any(axis=1)]
check[["Water Frontage Measurement", "Sewer Frontage Measurement"]].head(10)

    Water Frontage Measurement Sewer Frontage Measurement
121                         70                         70
122                         70                         70
123                       80.4                       80.4
124                         70                         70
125                         70                         70
126                      75.91                      75.93
127                      69.51                      69.53
128                         65                         65
129                      62.09                      62.13
130                       59.8                       59.8

The non-missing values in Water Frontage Measurement and Sewer Frontage Measurement are plain decimal numbers in feet (for example 70, 80.4, 75.91), so they can be converted to numeric directly. The two columns are nearly identical for each house, so they carry almost the same information; one of them, or their average, will be used as a feature instead of both. Missing values (about 1,300 per column) will be decided during feature preparation.

In [39]:
ressd_data["Property Influences"].value_counts().head(10)

Property Influences
COMMERCIAL ADJACENT         6041
PARK                        5881
EXTERNAL CORNER             5540
BUS ROUTE,MEDIUM TRAFFIC    4594
BUS ROUTE,LIGHT TRAFFIC     4462
BACK LANE                   4261
LIGHT TRAFFIC               3701
SCHOOL                      3112
HYDRO TRANSFORMER BOX       3034
INTERNAL CORNER             2643
Name: count, dtype: int64

Property Influences holds descriptive labels such as COMMERCIAL ADJACENT, PARK, EXTERNAL CORNER, BACK LANE, and SCHOOL, and some entries combine several influences separated by commas (for example, "BUS ROUTE,MEDIUM TRAFFIC"). This is why the column has 1,311 unique values. About half of the houses have no entry, which most likely means "no special influence." The column will be turned into a small set of 1/0 flags for the most common influences rather than used as raw text.

In [40]:
ressd_data["Zoning"].value_counts().head(10)

Zoning
R1M - RES - S F - MEDIUM     102580
R1L - RES - S F - LARGE       38745
R2 - RES - TWO FAMILY         18962
R1S - RES - S F - SMALL       12520
RR5 - RURAL RESIDENTIAL-5      1272
R1E - RES - S F - ESTATE       1006
RMFS - RES - MULTI-FAMILY       982
A - AGRICULTURAL                403
RR2 - RURAL RESIDENTIAL-2       384
RMFM - RES - MULTI-FAMILY       282
Name: count, dtype: int64

Zoning is dominated by a few residential codes: R1M (102,580 houses), R1L (38,745), R2 (18,962), and R1S (12,520). The remaining codes are rare, some with fewer than 300 houses. Zoning will be used as a categorical feature, with the rare codes grouped into an "Other" category.

### Duplicates

In [41]:
ressd_data.duplicated().sum()

np.int64(0)

In [42]:
duplicate_addresses = ressd_data[ressd_data["Full Address"].duplicated(keep=False)].sort_values("Full Address")

duplicate_addresses[[
    "Roll Number",
    "Full Address",
    "Total Living Area",
    "Year Built",
    "Total Assessed Value"
]]

,Roll Number,Full Address,Total Living Area,Year Built,Total Assessed Value
32027,3070294000,1016 KELSEY AVENUE,744,1935.0,"$256,000.00"
39636,3091584200,1016 KELSEY AVENUE,"1,088",2011.0,"$449,000.00"
32068,3070340000,1025 CLARENCE AVENUE,828,1979.0,"$349,000.00"
32069,3070340900,1025 CLARENCE AVENUE,802,2003.0,"$387,000.00"
45577,3093002470,1036 ROYSE AVENUE,890,2018.0,"$396,000.00"
...,...,...,...,...,...
202098,12097806765,95 BOREBANK STREET,"1,983",2018.0,"$904,000.00"
100038,6093405100,958 JOHN BRUCE ROAD E,"2,508",2019.0,"$826,000.00"
100519,6093459900,958 JOHN BRUCE ROAD E,"1,060",1967.0,"$469,000.00"
149407,8081225310,96 GUAY AVENUE,"1,356",2020.0,"$480,000.00"
149408,8081225315,96 GUAY AVENUE,"1,356",2020.0,"$480,000.00"

In [43]:
ressd_data[ressd_data["GISID"].duplicated(keep=False)].sort_values("GISID")

,Roll Number,Street Number,Unit Number,Street Suffix,Street Direction,Street Name,Street Type,Full Address,Neighbourhood Area,Market Region,...,Proposed Assessment Value 4,Proposed Property Class 5,Proposed Status 5,Proposed Assessment Value 5,Multiple Residences,Geometry,Dwelling Units,Centroid Lat,Centroid Lon,GISID
169914,11000241500,"1,637",NaN,NaN,NaN,MAIN,STREET,1637 MAIN STREET,SEVEN OAKS,"3, WEST KILDONAN / OLD KILDONAN",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.12001442944161 49.93244552...,1.0,49.932865,-97.120164,"30,204"
176901,11051784700,"1,637",NaN,NaN,NaN,MAIN,STREET,1637 MAIN STREET,SEVEN OAKS,"3, WEST KILDONAN / OLD KILDONAN",...,NaN,NaN,NaN,NaN,No,MULTIPOLYGON (((-97.12001442944161 49.93244552...,1.0,49.932865,-97.120164,"30,204"

No row is an exact duplicate of another (0 duplicated rows), and every Roll Number is unique. About 99 addresses appear twice (198 rows). In the rows inspected, the pairs have different living areas, years built, and assessed values, so they appear to be separate properties sharing an address (for example a lot split or a second unit) rather than duplicated records. One pair (96 Guay Avenue) has identical features and value but different roll numbers and could be two halves of one building or a double entry. The two rows sharing a GISID are both 1637 Main Street, one of which is the "OTHER" property class row that will be dropped. No rows will be removed for duplication.

## Cleaning decisions

**Scope and rows to remove**
- Keep only detached single dwellings (Property Use Code = RESSD): 177,823 rows.
- Drop the 56 land-only rows (missing Total Living Area, Year Built, Building Type, and Air Conditioning; 0 dwelling units).
- Drop the 10 rows with 0 dwelling units that do have building data (inconsistent assessed values, including $0).
- Drop the 30 rows with 2 or fewer rooms (room count is unreliable).
- Drop the 7 rows whose Property Class 1 is not RESIDENTIAL 1 (non-standard for detached houses).
- Drop the 23 rows still missing Basement after the drops above.
- Keep the 11 houses built in 2026 and the 29 houses with 15 or more rooms; revisit them in model error analysis.
- No duplicate rows to remove: no exact duplicates, and repeated addresses appear to be different properties. The shared-location pair involves 1637 Main Street, already dropped under Property Class.
- drop the row with a 0 assessed value.
- Rooms (6 missing) and Zoning (4 missing): drop them

**Type conversions**
- Total Assessed Value (target), Total Living Area, Assessed Land Area: remove "$" and "," and convert to numbers.
- Water and Sewer Frontage Measurement: convert to numbers.
- Year Built and Rooms: convert to integers after the drops.
- Basement, Basement Finish, Fire Place, Attached Garage, Detached Garage, Air Conditioning, Pool: encode Yes/No as 1/0.

**Columns to drop**
- Leakage: Assessed Value 1 to 5 (Assessed Value 1 is identical to the target), along with Property Class and Status 2 to 5.
- Empty: Number Floors (Condo), Total Proposed Assessment Value, all Proposed fields, Unit Number, Street Suffix, Street Direction.
- Constant or nearly constant: Property Use Code, Assessment Date, Current Assessment Year, Multiple Residences, Property Class 1, Status 1, Dwelling Units.
- Identifiers (kept for reference, not used as features): Roll Number, Street Number, Street Name, Street Type, Full Address, Detail URL, Geometry, GISID.

**Feature preparation**
- Property Influences: turn the most common influences into 1/0 flags, treating missing as "none."
- Zoning: group rare codes into "Other," then encode.
- Neighbourhood Area (203 categories) and Market Region (10): encode later; keep Centroid Lat/Lon for location features.
- Water and Sewer Frontage are nearly identical: keep one or their average, and decide how to treat missing values.
- Zoning: group rare codes into Other” to “Zoning: codes with fewer than 500 houses grouped into Other

**Checks after conversion**
- keep the large-lot rows, and handle the skew in Land Area during feature preparation.
- inspect the 34 rows between 1 and 50,000, then choose a cutoff.
- Low priority: about 100 repeated Full Address values.

## Cleaning the data

In [44]:
clean_data = ressd_data.copy()

In [45]:
clean_data["Total Living Area"] = clean_data["Total Living Area"].str.replace(",", "").astype(float)

In [46]:
clean_data["Assessed Land Area"] = clean_data["Assessed Land Area"].str.replace(",", "").astype(float)

In [47]:
clean_data["Total Assessed Value"] = clean_data["Total Assessed Value"].str.replace("$", "", regex=False).str.replace(",", "").astype(float)

In [48]:
clean_data[["Total Living Area", "Total Assessed Value","Assessed Land Area"]].dtypes

Total Living Area       float64
Total Assessed Value    float64
Assessed Land Area      float64
dtype: object

In [49]:
clean_data[["Total Living Area", "Total Assessed Value","Assessed Land Area"]].describe()

       Total Living Area  Total Assessed Value  Assessed Land Area
count      177767.000000          1.778230e+05        1.778230e+05
mean         1348.093870          4.439711e+05        6.860117e+03
std           532.423866          2.049001e+05        1.975523e+04
min           312.000000          0.000000e+00        1.005000e+03
25%           993.000000          3.310000e+05        4.254000e+03
50%          1209.000000          4.110000e+05        5.379000e+03
75%          1623.000000          5.340000e+05        6.441000e+03
max         14348.000000          8.975000e+06        4.201006e+06

Total Living Area, Total Assessed Value, and Assessed Land Area were converted from text to numbers. Assessed value has a median of 411,000 and ranges from 0 to 8,975,000; living area has a median of 1,209 sq ft and ranges from 312 to 14,348 sq ft. The 0 assessment is invalid, and extreme living area values need checking. Land area has a median of 5,379 sq ft, no missing values, and a maximum of 4,201,006 sq ft (about 96 acres) that needs investigation. The earlier 1 sq ft placeholder was removed with non-house properties.

In [50]:
clean_data["Water Frontage Measurement"] = clean_data["Water Frontage Measurement"].astype(float)
clean_data["Sewer Frontage Measurement"] = clean_data["Sewer Frontage Measurement"].astype(float)

In [51]:
print((clean_data["Total Assessed Value"] == 0).sum(), (clean_data["Total Assessed Value"] < 50000).sum())

1 35

Only 1 house has an assessed value of 0 (invalid), and 35 houses are assessed below 50,000. These low values are far below the median of 411,000 and are likely partial or unusual assessments. The 0 row will be dropped, and the other low-value rows will be inspected before choosing a cutoff.

In [52]:
clean_data.sort_values("Assessed Land Area", ascending=False)[["Full Address","Assessed Land Area","Total Living Area","Total Assessed Value"]].head(10)

,Full Address,Assessed Land Area,Total Living Area,Total Assessed Value
117,2790 WILKES AVENUE,4201006.0,4574.0,801000.0
146858,1600 TWO MILE ROAD,2289562.0,4643.0,2044000.0
72977,700 GARDEN VIEW DRIVE,1650815.0,1496.0,775000.0
81095,234 MAILHIOT ROAD,1240913.0,2679.0,1093000.0
145273,230 CHRISTIE ROAD,1155979.0,5747.0,1778000.0
140087,2855 ST MARY'S ROAD,1128133.0,1700.0,750000.0
125050,35 FOOT PLACE,934970.0,1584.0,962000.0
138193,1500 ST ANNE'S ROAD,826166.0,1344.0,546000.0
145325,1620 TWO MILE ROAD,726506.0,1790.0,768000.0
145324,3283 ST MARY'S ROAD,726486.0,1781.0,797000.0

The 10 largest lots range from about 726,000 to 4,201,006 sq ft (roughly 17 to 96 acres), on roads such as Two Mile Road, Mailhiot Road, and St. Mary's Road, so they are likely rural or acreage properties. The houses on them are normal in size (1,344 to 5,747 sq ft) and assessed at 546,000 to 2.0 million, so they appear to be genuine records rather than errors. They will be kept, but land area is extremely right-skewed (median 5,379 sq ft vs. a maximum of over 4 million), so it will need a transformation or a cap during feature preparation.

In [53]:
clean_data[clean_data["Total Assessed Value"] < 50000][[
    "Full Address",
    "Neighbourhood Area",
    "Total Living Area",
    "Year Built",
    "Total Assessed Value"
]]

,Full Address,Neighbourhood Area,Total Living Area,Year Built,Total Assessed Value
80206,143 NUTHATCH BAY,ROSSER-OLD KILDONAN,1976.0,2024.0,0.0
211010,632 MCGEE STREET,DANIEL McINTYRE,816.0,1905.0,40000.0
213103,618 WILLIAM AVENUE,WEST ALEXANDER,2183.0,1905.0,49000.0
214770,554 ROSS AVENUE,CENTENNIAL,1178.0,1901.0,43000.0
215001,611 PACIFIC AVENUE,CENTENNIAL,1064.0,1903.0,44000.0
215656,817 ALEXANDER AVENUE,WEST ALEXANDER,980.0,1914.0,47000.0
215692,260 BEACON STREET,WEST ALEXANDER,1011.0,1905.0,48000.0
218792,135 GROVE STREET,NORTH POINT DOUGLAS,1412.0,1885.0,30000.0
219341,425 FLORA AVENUE,DUFFERIN,1260.0,1902.0,30000.0
219576,641 DUFFERIN AVENUE,DUFFERIN,832.0,1901.0,33000.0
219600,631 FLORA AVENUE,DUFFERIN,544.0,1903.0,47000.0
219612,46 MCKENZIE STREET,DUFFERIN INDUSTRIAL,616.0,1901.0,44000.0
219635,700 STELLA AVENUE,DUFFERIN,984.0,1932.0,46000.0
219680,685 STELLA AVENUE,DUFFERIN,600.0,1914.0,33000.0
219690,689 FLORA AVENUE,DUFFERIN,1440.0,1907.0,30000.0
220994,444 MAGNUS AVENUE,WILLIAM WHYTE,1110.0,1903.0,30000.0
222322,185 MAGNUS AVENUE,NORTH POINT DOUGLAS,1221.0,1905.0,46000.0
222398,191 MCKENZIE STREET,WILLIAM WHYTE,442.0,1915.0,44000.0
222447,477 MAGNUS AVENUE,WILLIAM WHYTE,1016.0,1905.0,30000.0
222485,389 MAGNUS AVENUE,WILLIAM WHYTE,1598.0,1928.0,30000.0
222578,432 BURROWS AVENUE,WILLIAM WHYTE,864.0,1905.0,30000.0
222959,189 BURROWS AVENUE,NORTH POINT DOUGLAS,1344.0,1902.0,36000.0
223009,177 ALFRED AVENUE,NORTH POINT DOUGLAS,1216.0,1895.0,36000.0
223163,439 BURROWS AVENUE,WILLIAM WHYTE,1544.0,1914.0,30000.0
223232,380 ALFRED AVENUE,WILLIAM WHYTE,1020.0,1907.0,30000.0
223481,443 ALFRED AVENUE,WILLIAM WHYTE,1092.0,1909.0,30000.0
223494,397 ALFRED AVENUE,WILLIAM WHYTE,1400.0,1914.0,30000.0
223510,343 ALFRED AVENUE,WILLIAM WHYTE,1756.0,1901.0,30000.0
224040,361 ABERDEEN AVENUE,WILLIAM WHYTE,1332.0,1906.0,30000.0
224058,279 SALTER STREET,WILLIAM WHYTE,648.0,1905.0,42000.0
224234,891 ABERDEEN AVENUE,BURROWS CENTRAL,435.0,1913.0,49000.0
224393,325 BOYD AVENUE,ST JOHNS,1504.0,1910.0,31000.0
224509,350 COLLEGE AVENUE,ST JOHNS,1600.0,1911.0,30000.0
224659,499 REDWOOD AVENUE,ST JOHNS,647.0,1905.0,30000.0
226409,396 SALTER STREET,ST JOHNS,876.0,1909.0,30000.0

I decided to drop the 35 houses assessed below 50,000. They are all older inner-city homes with unusually low and repeated values (about half are exactly 30,000), and the dataset has no condition column that could explain them. Keeping them would add noise to the model. The limitation is that the model will tend to overpredict for the cheapest homes in these neighbourhoods.

In [54]:
(clean_data["Assessed Land Area"] > 20000).sum()

np.int64(2751)

In [55]:
(clean_data["Assessed Land Area"] < 10000).sum()

np.int64(165868)

Land area is concentrated in a narrow range: about houses (165,868) sit on lots under 10,000 sq ft, while 2,751 houses have more than 20,000 sq ft. This confirms that land area is strongly right-skewed. The large lots will be kept, and the skew will be handled during feature preparation with a transformation or a cap.

In [56]:
(clean_data["Assessed Land Area"] > 100000).sum()

np.int64(699)

### Dropping rows

Before dropping anything, I will build one rule (a True/False mask) for each drop decision and count how many rows each rule flags. Several rules overlap, so checking each count against my exploration results first lets me confirm that the right rows are dropped.

In [57]:
rule_zero_units = clean_data["Dwelling Units"] == 0
rule_few_rooms = clean_data["Rooms"] <= 2
rule_wrong_class = clean_data["Property Class 1"] != "RESIDENTIAL 1" #Property Class 1 has no missing values, so != is safe here
rule_missing_basement = clean_data["Basement"].isnull()
rule_low_value = clean_data["Total Assessed Value"] < 50000

print("Zero dwelling units:", rule_zero_units.sum())
print("2 or fewer rooms:", rule_few_rooms.sum())
print("Property class not RESIDENTIAL 1:", rule_wrong_class.sum())
print("Missing basement:", rule_missing_basement.sum())
print("Assessed value below $50,000:", rule_low_value.sum())

rows_to_drop = (
    rule_zero_units |
    rule_few_rooms |
    rule_wrong_class |
    rule_missing_basement |
    rule_low_value
)

print("Total unique rows flagged:", rows_to_drop.sum())

Zero dwelling units: 66
2 or fewer rooms: 30
Property class not RESIDENTIAL 1: 7
Missing basement: 79
Assessed value below $50,000: 35
Total unique rows flagged: 159

droping the rows

In [58]:
clean_data = clean_data[~rows_to_drop].copy()

In [59]:
clean_data.shape

(177664, 71)

In [60]:
print("Zero dwelling units:", (clean_data["Dwelling Units"] == 0).sum())
print("2 or fewer rooms:", (clean_data["Rooms"] <= 2).sum())
print("Property class not RESIDENTIAL 1:", (clean_data["Property Class 1"] != "RESIDENTIAL 1").sum())
print("Missing basement:", clean_data["Basement"].isnull().sum())
print("Assessed value below $50,000:", (clean_data["Total Assessed Value"] < 50000).sum())

Zero dwelling units: 0
2 or fewer rooms: 0
Property class not RESIDENTIAL 1: 0
Missing basement: 0
Assessed value below $50,000: 0

After dropping the 159 flagged rows, the table has 177,664 houses, which matches the expected count. Re-running each of the five rules on the new table returns 0, confirming that all intended rows were removed and no rule was missed.

In [61]:
clean_data.info()

<class 'pandas.DataFrame'>
Index: 177664 entries, 0 to 245461
Data columns (total 71 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Roll Number                      177664 non-null  int64
 1   Street Number                    177663 non-null  str
 2   Unit Number                      12 non-null      object
 3   Street Suffix                    102 non-null     str
 4   Street Direction                 8819 non-null    str
 5   Street Name                      177664 non-null  str
 6   Street Type                      177185 non-null  str
 7   Full Address                     177664 non-null  str
 8   Neighbourhood Area               177664 non-null  str
 9   Market Region                    177664 non-null  str
 10  Total Living Area                177664 non-null  float64
 11  Building Type                    177664 non-null  str
 12  Basement                         177664 non-null  str
 13  Basement Finish                  177664 non-null  str
 14  Year Built                       177664 non-null  float64
 15  Rooms                            177658 non-null  float64
 16  Air Conditioning                 177664 non-null  str
 17  Fire Place                       177664 non-null  str
 18  Attached Garage                  177664 non-null  str
 19  Detached Garage                  177664 non-null  str
 20  Pool                             177664 non-null  str
 21  Number Floors (Condo)            0 non-null       float64
 22  Property Use Code                177664 non-null  str
 23  Assessed Land Area               177664 non-null  float64
 24  Water Frontage Measurement       176352 non-null  float64
 25  Sewer Frontage Measurement       176292 non-null  float64
 26  Property Influences              87796 non-null   str
 27  Zoning                           177660 non-null  str
 28  Total Assessed Value             177664 non-null  float64
 29  Total Proposed Assessment Value  0 non-null       float64
 30  Assessment Date                  177664 non-null  str
 31  Detail URL                       177664 non-null  str
 32  Current Assessment Year          177664 non-null  int64
 33  Property Class 1                 177664 non-null  str
 34  Status 1                         177664 non-null  str
 35  Assessed Value 1                 177664 non-null  str
 36  Property Class 2                 128 non-null     str
 37  Status 2                         128 non-null     str
 38  Assessed Value 2                 128 non-null     str
 39  Property Class 3                 3 non-null       str
 40  Status 3                         3 non-null       str
 41  Assessed Value 3                 3 non-null       str
 42  Property Class 4                 0 non-null       str
 43  Status 4                         0 non-null       str
 44  Assessed Value 4                 0 non-null       str
 45  Property Class 5                 0 non-null       str
 46  Status 5                         0 non-null       str
 47  Assessed Value 5                 0 non-null       str
 48  Proposed Assessment Year         0 non-null       float64
 49  Proposed Assessment Date         0 non-null       float64
 50  Proposed Property Class 1        0 non-null       float64
 51  Proposed Status 1                0 non-null       float64
 52  Proposed Assessment Value 1      0 non-null       float64
 53  Proposed Property Class 2        0 non-null       float64
 54  Proposed Status 2                0 non-null       float64
 55  Proposed Assessment Value 2      0 non-null       float64
 56  Proposed Property Class 3        0 non-null       float64
 57  Proposed Status 3                0 non-null       float64
 58  Proposed Assessment Value 3      0 non-null       float64
 59  Proposed Property Class 4        0 non-null       float64
 60  Proposed Status 4                0 non-null       float64
 61  Proposed Assessment Value 4      0 non-null       float64
 62  Proposed Property Class 5        0 non-null       float64
 63  Proposed Status 5                0 non-null       float64
 64  Proposed Assessment Value 5      0 non-null       float64
 65  Multiple Residences              177664 non-null  str
 66  Geometry                         177664 non-null  str
 67  Dwelling Units                   177664 non-null  float64
 68  Centroid Lat                     177664 non-null  float64
 69  Centroid Lon                     177664 non-null  float64
 70  GISID                            177664 non-null  str
dtypes: float64(29), int64(2), object(1), str(39)
memory usage: 206.8+ MB

In [62]:
# Leakage columns
leakage_cols = ([f"Assessed Value {i}" for i in range(1, 6)] + [f"Property Class {i}" for i in range(2, 6)] + [f"Status {i}" for i in range(2, 6)])

# Empty columns
empty_cols = (["Number Floors (Condo)", "Total Proposed Assessment Value", "Unit Number", "Street Suffix", "Street Direction"] +[c for c in clean_data.columns if c.startswith("Proposed")])

# Constant or nearly constant columns
constant_cols = ["Property Use Code","Assessment Date","Current Assessment Year","Multiple Residences","Property Class 1","Status 1","Dwelling Units"]

clean_data = clean_data.drop(columns=leakage_cols + empty_cols + constant_cols)

In [63]:
clean_data.shape

(177664, 29)

In [64]:
clean_data.info()

<class 'pandas.DataFrame'>
Index: 177664 entries, 0 to 245461
Data columns (total 29 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Roll Number                 177664 non-null  int64
 1   Street Number               177663 non-null  str
 2   Street Name                 177664 non-null  str
 3   Street Type                 177185 non-null  str
 4   Full Address                177664 non-null  str
 5   Neighbourhood Area          177664 non-null  str
 6   Market Region               177664 non-null  str
 7   Total Living Area           177664 non-null  float64
 8   Building Type               177664 non-null  str
 9   Basement                    177664 non-null  str
 10  Basement Finish             177664 non-null  str
 11  Year Built                  177664 non-null  float64
 12  Rooms                       177658 non-null  float64
 13  Air Conditioning            177664 non-null  str
 14  Fire Place                  177664 non-null  str
 15  Attached Garage             177664 non-null  str
 16  Detached Garage             177664 non-null  str
 17  Pool                        177664 non-null  str
 18  Assessed Land Area          177664 non-null  float64
 19  Water Frontage Measurement  176352 non-null  float64
 20  Sewer Frontage Measurement  176292 non-null  float64
 21  Property Influences         87796 non-null   str
 22  Zoning                      177660 non-null  str
 23  Total Assessed Value        177664 non-null  float64
 24  Detail URL                  177664 non-null  str
 25  Geometry                    177664 non-null  str
 26  Centroid Lat                177664 non-null  float64
 27  Centroid Lon                177664 non-null  float64
 28  GISID                       177664 non-null  str
dtypes: float64(9), int64(1), str(19)
memory usage: 136.7 MB

After dropping the leakage, empty, and constant columns, 29 columns remain and the row count is unchanged at 177,664. All the Assessed Value 1 to 5 columns are gone, so the model cannot see the target through a side door. The remaining columns are the identifiers (kept for reference only) and the candidate features. Missing values still remain in Rooms (6), Zoning (4), the two frontage columns (about 1,300 each), and Property Influences (about half, which means "none"). These will be handled in the next steps.

In [65]:
clean_data = clean_data.drop(columns=[
    "Geometry",
    "GISID",
    "Street Number",
    "Street Name",
    "Street Type"
])

In [66]:
clean_data.shape

(177664, 24)

In [67]:
clean_data.info()

<class 'pandas.DataFrame'>
Index: 177664 entries, 0 to 245461
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Roll Number                 177664 non-null  int64
 1   Full Address                177664 non-null  str
 2   Neighbourhood Area          177664 non-null  str
 3   Market Region               177664 non-null  str
 4   Total Living Area           177664 non-null  float64
 5   Building Type               177664 non-null  str
 6   Basement                    177664 non-null  str
 7   Basement Finish             177664 non-null  str
 8   Year Built                  177664 non-null  float64
 9   Rooms                       177658 non-null  float64
 10  Air Conditioning            177664 non-null  str
 11  Fire Place                  177664 non-null  str
 12  Attached Garage             177664 non-null  str
 13  Detached Garage             177664 non-null  str
 14  Pool                        177664 non-null  str
 15  Assessed Land Area          177664 non-null  float64
 16  Water Frontage Measurement  176352 non-null  float64
 17  Sewer Frontage Measurement  176292 non-null  float64
 18  Property Influences         87796 non-null   str
 19  Zoning                      177660 non-null  str
 20  Total Assessed Value        177664 non-null  float64
 21  Detail URL                  177664 non-null  str
 22  Centroid Lat                177664 non-null  float64
 23  Centroid Lon                177664 non-null  float64
dtypes: float64(9), int64(1), str(14)
memory usage: 76.3 MB

The remaining columns are the candidate features plus a few identifier columns (Roll Number, Full Address, Detail URL) that are not used for modeling but will be needed later to look up houses the model predicts badly and to show addresses in the app.

In [68]:
clean_data[clean_data["Rooms"].isnull()][["Full Address","Total Living Area","Total Assessed Value"]]

               Full Address  Total Living Area  Total Assessed Value
9536    1264 LIBERTY STREET             2914.0             1230000.0
64090   118 GOLDEN BOY LANE             2247.0              690000.0
96439      212 DOCKSIDE WAY             1909.0              567000.0
99268      15 SEASIDE DRIVE             2222.0              648000.0
125545    1831 LOGAN AVENUE              831.0              195000.0
223116   559 BURROWS AVENUE              896.0              266000.0

6 houses are missing a Rooms value. They look like ordinary houses, so the room count is simply unrecorded. Since this is only 6 rows , I will drop them rather than guess a value.

In [69]:
clean_data[clean_data["Zoning"].isnull()][["Full Address","Total Living Area","Total Assessed Value"]]

              Full Address  Total Living Area  Total Assessed Value
9466    532 MUNICIPAL ROAD             1804.0              826000.0
44062      885 LYON STREET             1616.0              389000.0
44063      881 LYON STREET             1638.0              436000.0
148139    67 SADLER AVENUE             1432.0              495000.0

4 houses are missing a Zoning value. They look like ordinary houses , so the zoning is simply unrecorded. Since this is only 4 rows, I will drop them rather than invent a category.

In [70]:
clean_data = clean_data.dropna(subset=["Rooms"]).copy()
clean_data = clean_data.dropna(subset=["Zoning"]).copy()

In [71]:
clean_data["Rooms"] = clean_data["Rooms"].astype(int)
clean_data["Year Built"] = clean_data["Year Built"].astype(int)

In [72]:
clean_data.shape

(177654, 24)

In [73]:
clean_data[["Rooms", "Year Built"]].dtypes

Rooms         int64
Year Built    int64
dtype: object

In [74]:
yes_no_cols = [
    "Basement",
    "Basement Finish",
    "Fire Place",
    "Attached Garage",
    "Detached Garage",
    "Air Conditioning",
    "Pool"
]
for col in yes_no_cols:
    clean_data[col] = clean_data[col].map({"Yes": 1, "No": 0})

In [75]:
for col in yes_no_cols:
    print(f"\n{col}:")
    print(clean_data[col].value_counts(dropna=False))

Basement:
Basement
1    173773
0      3881
Name: count, dtype: int64

Basement Finish:
Basement Finish
1    128209
0     49445
Name: count, dtype: int64

Fire Place:
Fire Place
0    120234
1     57420
Name: count, dtype: int64

Attached Garage:
Attached Garage
0    116165
1     61489
Name: count, dtype: int64

Detached Garage:
Detached Garage
0    94419
1    83235
Name: count, dtype: int64

Air Conditioning:
Air Conditioning
1    133528
0     44126
Name: count, dtype: int64

Pool:
Pool
0    171863
1      5791
Name: count, dtype: int64

In [76]:
clean_data["Zoning"].value_counts()

Zoning
R1M - RES - S F - MEDIUM      102515
R1L - RES - S F - LARGE        38728
R2 - RES - TWO FAMILY          18916
R1S - RES - S F - SMALL        12497
RR5 - RURAL RESIDENTIAL-5       1270
R1E - RES - S F - ESTATE        1005
RMFS - RES - MULTI-FAMILY        977
A - AGRICULTURAL                 402
RR2 - RURAL RESIDENTIAL-2        383
RMFM - RES - MULTI-FAMILY        282
C1 - COM - NEIGHBOURHOOD         153
C2 - COM - COMMUNITY             150
M2 - MANUFCTRNG - GENERAL         72
M1 - MANUFCTRNG - LIGHT           69
PR1 - PRKS&REC-PASSIVE            49
R14 - SINGLE FAMILY               48
M3 - MANUFCTRNG - HEAVY           30
CMU - COMMERCIAL-MIXED USE        27
RMFL - RES - MULTI-FAMILY         16
M - MULTIPLE-USE                  12
R135 - SINGLE FAMILY              11
RMU - RES - MIX USE                9
PR2 - PRKS&REC-ACTIVE              5
PR3 - PRKS&REC-REGIONAL            4
C3 - COM - CORRIDOR                3
R155 - SINGLE FAMILY               3
R15 - SINGLE FAMILY                3
155A - SINGLE FAMILY               3
120A - SINGLE FAMILY               2
R125 - SINGLE FAMILY               2
R13 - SINGLE FAMILY                2
RM1 - MULTIPLE FAMILY              1
R120 - SINGLE FAMILY               1
A5 - AGR - MIN 5 ACRES             1
D - DOWNTOWN LIVING                1
C - CHARACTER                      1
R2A - TWO FAMILY                   1
Name: count, dtype: int64

In [77]:
zoning_counts = clean_data["Zoning"].value_counts()
rare_zoning = zoning_counts[zoning_counts < 500].index
clean_data.loc[clean_data["Zoning"].isin(rare_zoning), "Zoning"] = "Other"

In [78]:
clean_data["Zoning"].value_counts()

Zoning
R1M - RES - S F - MEDIUM     102515
R1L - RES - S F - LARGE       38728
R2 - RES - TWO FAMILY         18916
R1S - RES - S F - SMALL       12497
Other                          1746
RR5 - RURAL RESIDENTIAL-5      1270
R1E - RES - S F - ESTATE       1005
RMFS - RES - MULTI-FAMILY       977
Name: count, dtype: int64

In [79]:
clean_data["Zoning"].nunique()

8

Zoning had 37 codes, but only 7 have more than 900 houses. I grouped every code with fewer than 500 houses into "Other". This leaves 8 categories.

In [80]:
 clean_data["Water Frontage Measurement"].isnull().sum()

np.int64(1311)

In [81]:
clean_data["Sewer Frontage Measurement"].isnull().sum()

np.int64(1371)

In [82]:
(clean_data["Water Frontage Measurement"].isnull() & clean_data["Sewer Frontage Measurement"].isnull()).sum()

np.int64(1307)

Water Frontage Measurement is missing for 1,311 houses and Sewer Frontage Measurement for 1,371. The gaps overlap heavily: 1,307 houses are missing both, so the missing values are concentrated in the same properties rather than scattered at random. In total about 1,375 houses are missing at least one of the two.

In [83]:
missing_water = clean_data["Water Frontage Measurement"].isnull()

print(clean_data.loc[missing_water, "Assessed Land Area"].median())

102420.0

In [84]:
clean_data.loc[missing_water, "Neighbourhood Area"].value_counts().head(10)

Neighbourhood Area
ST VITAL PERIMETER S    620
WILKES SOUTH            240
KIL-CONA PARK           118
TRANSCONA SOUTH          83
ROSSER-OLD KILDONAN      78
TURNBULL DRIVE           35
PERRAULT                 24
WAVERLEY WEST-B          19
GRASSIE                  15
ROYALWOOD                13
Name: count, dtype: int64

Missing Water Frontage Measurement values were filled using Sewer Frontage Measurement where available (4 houses), and with 0 for the rest, since the missing values most likely mean no connection. Sewer Frontage Measurement was then dropped because it duplicates the water column. Water frontage now has no missing values, and the table has 177,654 rows and 23 columns.

In [85]:
clean_data["Water Frontage Measurement"] = (
    clean_data["Water Frontage Measurement"]
    .fillna(clean_data["Sewer Frontage Measurement"])
    .fillna(0)
)

In [86]:
clean_data = clean_data.drop(columns=["Sewer Frontage Measurement"])

In [87]:
clean_data["Water Frontage Measurement"].isnull().sum()

np.int64(0)

In [88]:
clean_data.shape

(177654, 23)

In [89]:
influences = (clean_data["Property Influences"].dropna().str.split(",").explode().str.strip())
influences.value_counts().head(15)

Property Influences
BUS ROUTE                  22217
LIGHT TRAFFIC              16882
EXTERNAL CORNER            16066
MEDIUM TRAFFIC             13776
COMMERCIAL ADJACENT        13567
PARK                       11219
BACK LANE                   8124
HEAVY TRAFFIC               6724
SCHOOL                      6167
HYDRO TRANSFORMER BOX       5758
INTERNAL CORNER             4744
COMMUNITY CLUB BUILDING     2902
RAIL LINE                   2734
COMMERCIAL INFLUENCE        2148
RETENTION POND ADJACENT     2007
Name: count, dtype: int64

In [90]:
influences.nunique()

41

Property Influences contains 41 distinct labels. The most common are BUS ROUTE, LIGHT TRAFFIC, and EXTERNAL CORNER. I will create 15 binary flags for influences appearing in at least 2,000 houses, treating missing values as none.

In [91]:
light = clean_data["Property Influences"].str.contains("LIGHT TRAFFIC", na=False)
medium = clean_data["Property Influences"].str.contains("MEDIUM TRAFFIC", na=False)
heavy = clean_data["Property Influences"].str.contains("HEAVY TRAFFIC", na=False)

traffic_count = light.astype(int) + medium.astype(int) + heavy.astype(int)

(traffic_count >= 2).sum()

np.int64(0)

In [92]:
clean_data["Traffic Level"] = (
    clean_data["Property Influences"].str.contains("LIGHT TRAFFIC", na=False).astype(int) * 1 +
    clean_data["Property Influences"].str.contains("MEDIUM TRAFFIC", na=False).astype(int) * 2 +
    clean_data["Property Influences"].str.contains("HEAVY TRAFFIC", na=False).astype(int) * 3
)

LIGHT TRAFFIC, MEDIUM TRAFFIC, and HEAVY TRAFFIC never appear together (0 houses have more than one), so they were combined into a single Traffic Level column: 0 for no traffic influence, 1 for light, 2 for medium, and 3 for heavy. This uses one column instead of three, though it assumes the levels are evenly spaced.

In [93]:
clean_data["Traffic Level"].value_counts().sort_index()

Traffic Level
0    140272
1     16882
2     13776
3      6724
Name: count, dtype: int64

In [94]:
influence_counts = influences.value_counts()

traffic_names = ["LIGHT TRAFFIC", "MEDIUM TRAFFIC", "HEAVY TRAFFIC"]

selected_influences = [
    influence
    for influence in influence_counts[influence_counts >= 2000].index
    if influence not in traffic_names
]

In [95]:
len(selected_influences)

12

In [96]:
influence_labels = clean_data["Property Influences"].fillna("").str.split(",")
for influence in selected_influences:
    clean_data[f"Influence: {influence}"] = influence_labels.apply(
        lambda labels: int(influence in [label.strip() for label in labels])
    )

In [97]:
for influence in selected_influences:
    flag_sum = clean_data[f"Influence: {influence}"].sum()
    expected_count = influence_counts.get(influence, 0)

    status = "MATCH" if flag_sum == expected_count else "MISMATCH"

    print(
        f"{influence}: flag = {flag_sum}, "
        f"expected = {expected_count}, {status}"
    )

BUS ROUTE: flag = 22217, expected = 22217, MATCH
EXTERNAL CORNER: flag = 16066, expected = 16066, MATCH
COMMERCIAL ADJACENT: flag = 13567, expected = 13567, MATCH
PARK: flag = 11219, expected = 11219, MATCH
BACK LANE: flag = 8124, expected = 8124, MATCH
SCHOOL: flag = 6167, expected = 6167, MATCH
HYDRO TRANSFORMER BOX: flag = 5758, expected = 5758, MATCH
INTERNAL CORNER: flag = 4744, expected = 4744, MATCH
COMMUNITY CLUB BUILDING: flag = 2902, expected = 2902, MATCH
RAIL LINE: flag = 2734, expected = 2734, MATCH
COMMERCIAL INFLUENCE: flag = 2148, expected = 2148, MATCH
RETENTION POND ADJACENT: flag = 2007, expected = 2007, MATCH

Property Influences was turned into 12 flag columns, one for each influence found on at least 2,000 houses (excluding the three traffic labels, which became Traffic Level). Each entry was split into its separate labels and matched exactly, and every flag's total equals the influence's count from the earlier split (for example, 22,217 houses for BUS ROUTE and 11,219 for PARK). Missing values were treated as "none" (all flags 0). The original text column was then dropped.

In [98]:
clean_data = clean_data.drop(columns=["Property Influences"])
clean_data.shape

(177654, 35)

In [99]:
clean_data.isnull().sum()

Roll Number                           0
Full Address                          0
Neighbourhood Area                    0
Market Region                         0
Total Living Area                     0
Building Type                         0
Basement                              0
Basement Finish                       0
Year Built                            0
Rooms                                 0
Air Conditioning                      0
Fire Place                            0
Attached Garage                       0
Detached Garage                       0
Pool                                  0
Assessed Land Area                    0
Water Frontage Measurement            0
Zoning                                0
Total Assessed Value                  0
Detail URL                            0
Centroid Lat                          0
Centroid Lon                          0
Traffic Level                         0
Influence: BUS ROUTE                  0
Influence: EXTERNAL CORNER            0
Influence: COMMERCIAL ADJACENT        0
Influence: PARK                       0
Influence: BACK LANE                  0
Influence: SCHOOL                     0
Influence: HYDRO TRANSFORMER BOX      0
Influence: INTERNAL CORNER            0
Influence: COMMUNITY CLUB BUILDING    0
Influence: RAIL LINE                  0
Influence: COMMERCIAL INFLUENCE       0
Influence: RETENTION POND ADJACENT    0
dtype: int64

In [100]:
clean_data.dtypes

Roll Number                             int64
Full Address                              str
Neighbourhood Area                        str
Market Region                             str
Total Living Area                     float64
Building Type                             str
Basement                                int64
Basement Finish                         int64
Year Built                              int64
Rooms                                   int64
Air Conditioning                        int64
Fire Place                              int64
Attached Garage                         int64
Detached Garage                         int64
Pool                                    int64
Assessed Land Area                    float64
Water Frontage Measurement            float64
Zoning                                    str
Total Assessed Value                  float64
Detail URL                                str
Centroid Lat                          float64
Centroid Lon                          float64
Traffic Level                           int64
Influence: BUS ROUTE                    int64
Influence: EXTERNAL CORNER              int64
Influence: COMMERCIAL ADJACENT          int64
Influence: PARK                         int64
Influence: BACK LANE                    int64
Influence: SCHOOL                       int64
Influence: HYDRO TRANSFORMER BOX        int64
Influence: INTERNAL CORNER              int64
Influence: COMMUNITY CLUB BUILDING      int64
Influence: RAIL LINE                    int64
Influence: COMMERCIAL INFLUENCE         int64
Influence: RETENTION POND ADJACENT      int64
dtype: object

In [101]:
clean_data[["Total Living Area", "Assessed Land Area", "Total Assessed Value"]].describe()

       Total Living Area  Assessed Land Area  Total Assessed Value
count      177654.000000        1.776540e+05          1.776540e+05
mean         1347.951710        6.858902e+03          4.441082e+05
std           531.965872        1.975522e+04          2.045257e+05
min           312.000000        1.005000e+03          5.000000e+04
25%           993.250000        4.254000e+03          3.310000e+05
50%          1209.000000        5.381000e+03          4.110000e+05
75%          1622.000000        6.441000e+03          5.350000e+05
max         14348.000000        4.201006e+06          8.975000e+06

In [102]:
clean_data.sort_values("Total Living Area", ascending=True)[
    ["Full Address", "Total Living Area", "Rooms", "Total Assessed Value"]
].head(5)

,Full Address,Total Living Area,Rooms,Total Assessed Value
237229,442 WILLIAM NEWTON AVENUE,312.0,3,143000.0
221835,1127 MANITOBA AVENUE,324.0,3,109000.0
13966,243 GREENE AVENUE,343.0,3,162000.0
222744,1051 MAGNUS AVENUE,346.0,3,85000.0
237078,605 HERBERT AVENUE,360.0,3,137000.0

In [103]:
clean_data.sort_values("Total Living Area", ascending=False)[
    ["Full Address", "Total Living Area", "Rooms", "Total Assessed Value"]
].head(5)

,Full Address,Total Living Area,Rooms,Total Assessed Value
188898,1015 WELLINGTON CRESCENT,14348.0,14,8975000.0
166638,570 PARK BOULEVARD W,11197.0,16,2532000.0
148558,300 DUNKIRK DRIVE,10334.0,14,2981000.0
77439,66 NIHAL BAY,10229.0,16,2147000.0
169702,550 PARK BOULEVARD W,9860.0,18,5579000.0

The cleaned table has no missing values, and every feature is numeric except four categorical columns (Neighbourhood Area, Market Region, Building Type, and Zoning), which will be encoded in the modeling stage. Total Assessed Value now starts at $50,000, confirming the low-value rows were removed. I also checked the extremes in living area: the smallest houses (312 to 360 sq ft) and the largest (9,860 to 14,348 sq ft) have room counts and values that fit their size, so all were kept. The large houses will be revisited during model error analysis.

## Summary

**Rows and columns:** The original City of Winnipeg Assessment Parcels dataset had 245,487 rows and 71 columns. After keeping only detached single dwellings (RESSD) and cleaning the data, I ended up with **177,654 houses and 35 columns**.

**Main data quality issues:**

* **Data leakage:** Assessed Value 1 to 5 were duplicates of Total Assessed Value, so I dropped them to prevent leakage.
* **Formatting:** I converted Total Assessed Value, Total Living Area, and Assessed Land Area from text to numeric values. I also converted Year Built and Rooms to integers and Yes/No columns to 1/0.
* **Missing values:** I removed empty or useless columns and 56 land-only parcels. I also removed rows missing Rooms or Zoning. Missing frontage values were filled with 0 because they likely mean no frontage.
* **Invalid records:** I removed houses with 0 dwelling units, 2 or fewer rooms, non-residential property classes, or assessed values below $50,000.
* **Text cleanup:** I reduced Zoning from 37 codes to 8 and converted Property Influences into 12 binary flags and a combined Traffic Level column.

**Next steps:** The cleaned dataset has no missing values. Four categorical columns remain: Neighbourhood Area, Market Region, Building Type, and Zoning. I will encode these during modelling, then work on feature engineering, split the data into training and testing sets, and train the models. Possible features include log-transforming land area and calculating distance to downtown using coordinates.

The target is Total Assessed Value, which represents the assessed property value, not the actual sale price.

In [104]:
clean_data.to_csv("../data/clean_ressd_parcels.csv", index=False)